presentations.txt

Add a presentation about Amazon Machine Learning by mrkn

---

presentations.txt

たべみるのHA構成について、えびスタ#2で話したスライドです

Add a slide for ebi-sta #2

---

presentations.txt

add slide talked in jasst 15 tohoku

---

presentations.txt

https://speakerdeck.com/mirakui/developer-productivity-in-cookpad

Add クックパッドはなぜ開発しやすいか

---

presentations.txt

Add URL of github study slide

---

presentations.txt

[NLP若手の会 第10回シンポジウム](http://yans.anlp.jp/modules/menu/main.php?page_id=112&op=change_page)で発表したスライドです

Add the URL of the presentation for YANS 2015

---

presentations.txt

Add some slides.
- Engineer talk night series
- http://staffblog.cookpad.com/entry/2015/11/30/153053
- http://staffblog.cookpad.com/entry/2015/10/26/161609
- System test automation conference 2015
- https://4deb81d081862e256eb240be7c.doorkeeper.jp/events/34145
Please merge and publish.

add some slides

---

presentations.txt

Added my slides I presented for:
- RubyKaigi 2015
- High Performance Template Engine: https://speakerdeck.com/k0kubun/high-performance-template-engine
- How I debugged debugger: https://speakerdeck.com/k0kubun/how-i-debugged-debugger-number-rubykaigi-1
- Cookpad TechConf 2016
- Railsアプリ開発環境の高速化: https://speakerdeck.com/k0kubun/railsapurikai-fa-huan-jing-falsegao-su-hua

Add slides for RubyKaigi and Cookpad TechConf

---

presentations.txt

Add Developers.IO Meetup slide

---

presentations.txt

Add slides by harashima

---

presentations.txt

Please merge and publish :pray: :pray:

Add some slides by deguchi

---

presentations.txt

Add Tada's slides

---

.gitignore
.travis.yml
Rakefile

* .travis.yml: Support travis ci
* Rakefile: generate artifacts on ./out directory
* .gitignore: Ignore ./out directory

Automate deployments using travis-ci.org

---

presentations.txt

Add slides for Rails Upgrade Casual Talks

---

presentations.txt

Add slides for AWS Summit Tokyo 2016

---

presentations.txt

My talk at devsumi 2016 wintter

add devsumi

---

presentations.txt

My talk at CEDEC 2016
...... and I forgot SeasarCon and AWS Casual Talks. 🙏

Add yoshiori's slides

---

presentations.txt

Added my presentation slide on Cookpad Tech Kitchen 2016/9/13
http://cookpad-tech-kitchen.connpass.com/event/37908/

Add CDC Testing on iOS on Cookpad Tech Kitchen2

---

presentations.txt

Added my slides for RubyKaigi 2016.
http://rubykaigi.org/2016/presentations/k0kubun.html

Add slides for RubyKaigi 2016

---

presentations.txt

https://ookami.connpass.com/event/50553/
:pray:

Add slides on fastlane Meetup Japan

---

lib/presentations/page/slide_share.rb
presentations.txt

I'm not sure how to order the list...

Add my OedoRubyKaigi06 presentation

---

presentations.txt

https://yj-meetup.connpass.com/event/57153/
🙏

Add slides for CAMPFIRE iOS #2

---

presentations.txt

https://forkwell.connpass.com/event/51332/
🙏

Add slides for Forkwell Meetup #4.

---

presentations.txt

Add ayemos's presentations

---

presentations.txt

http://www.reddotrubyconf.com/#juanitofatas

Add Data Migration with Confidence at RedDotRubyConf 2017

---

presentations.txt

https://speakerdeck.com/pocke/a-parser-based-syntax-highlighter

Add pocke's RubyKaigi presentation

---

presentations.txt

Add slides for Tokyo Rails#37 talks
